# Getting Started

In [ ]:
# Load library
import numpy as np

# 1. Creation in NumPy
* Goal：Learn how to create 1-d and 2-d NumPy arrays.
* Examples:
 * `np.array()`
 * `np.arange()`
 * `np.random.randint()`
 * `np.random.rand()`
 * `np.random.randn()`
 * `np.zeros()`

## Create a one-dimensional array

### Create a 1-d array with specific data
* Use `np.array()`

In [ ]:
# Create a 1-d array "account_length" - simply pass a Python list
arr_1d = np.array([107, 137, 84, 75])

print(arr_1d)

[107 137  84  75]


## Generate a 1-d array of any Length(size)
* Use `np.arange(size)`

In [ ]:
# Create a 1-d array with length/size 5
# The default start value is 0, return an array of evenly spaced values.
arr_1d = np.arange(5)

print(arr_1d)

[0 1 2 3 4]


## Generate a 1-d array of 6 random intergers between 1 and 9
* Use `np.random.randint(low_inclusive, high_exclusive, size)`

In [ ]:
## Use
arr_1d = np.random.randint(1, 10, 6)

print(arr_1d)

[3 3 7 8 5 6]


## Generate a 1-d array of 10 random **floats** between 0 and 1(exlusive)
* Use `np.random.rand(size)`
* It generates random floating-point numbers from a continuous uniform distribution [0, 1).

In [ ]:
## Generate a 1-d array of 7 random floats between 0 and 1
arr_1d = np.random.random(7)

arr_1d

array([0.4490017 , 0.21039037, 0.56742813, 0.65728315, 0.8673746 ,
       0.1524951 , 0.77712815])

## Generate a 1-d array of 6 elements from the “standard normal” distribution



In [ ]:
# The 6 elements are from the “standard normal” distribution
np.random.randn(6)

array([ 0.67897767,  0.09144135,  0.04196689, -0.18684535, -0.7836992 ,
        0.03160258])

## Create a 1-d array of Zeros
* Use `np.zeros(size)`

In [ ]:
arr_1d = np.zeros(5)

arr_1d

array([0., 0., 0., 0., 0.])

## Create a two-dimensional array (matrix)


### Create a 2-d array with specific data
* Use `np.array()`

In [ ]:
# Create a 2-d array (matrix) - simplyly pass a list of Python list
arr_2d = np.array([
           [26, 1],
           [0,  0],
           [0,  2],
           [0,  3]
])

print(arr_2d)

[[26  1]
 [ 0  0]
 [ 0  2]
 [ 0  3]]


## Create a 6 x 2 matrix of random integers between 1 and 99(inclusive)

In [ ]:
# Create a 6 x 2 matrix of random integers between 1 and 99(inclusive)
arr_2d = np.random.randint(1, 100, (6, 2))

print(arr_2d)

[[61 76]
 [95 41]
 [97 65]
 [15 29]
 [61 54]
 [40 69]]


## Generate a 4 x 3 Matrix of random floats between 0 and 1(exlusive)


In [ ]:
# Generate a 4 x 3 Matrix of random floats between 0 and 1(exlusive)
arr_2d = np.random.rand(4, 3) # 1st dimension, 2nd dimension

print(arr_2d)

[[0.27420709 0.58337212 0.7591601 ]
 [0.94180473 0.50848209 0.13282079]
 [0.38707719 0.05464725 0.36587647]
 [0.11705363 0.6803763  0.49469947]]


## Generate a 2 x 3 Matrix where element are from the “standard normal” distribution


In [ ]:
# The 2 X 3 matrix are from the “standard normal” distribution
np.random.randn(2, 3)

array([[ 0.46990292, -1.46633438, -0.46041929],
       [ 0.6085436 ,  0.23749974,  1.49219865]])

## Create a 4 x 6 **Matrix** of Zeros

In [ ]:
# Generate a 4 x 6 Matrix of 0
arr_2d = np.zeros((4, 6)) # tuple of (row, col)

print(arr_2d)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Create a 3 x 3 identity matrix
* In linear algebra, an identity matrix is a matrix of with ones on the main diagonal and zeros elsewhere.

In [ ]:
# Use np.eye()
identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
id_matrix = np.identity(3)

id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Describing a NumPy Array  - `shape`, `size`, `ndim`

In [ ]:
arr = np.array([
  [1,2,3],
  [4,5,6,7,8],
  [9]
])

<ipython-input-23-e244264a0133>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([


In [ ]:
#
arr_1d = np.array([107, 137, 84, 75])

print(arr_1d)

[107 137  84  75]


In [ ]:
arr_1d.shape


# It only has one number is because it only has 1 dimension

(4,)

In [ ]:
arr_2d = np.array([
           [26, 1],
           [0,  0],
           [0,  2],
           [0,  3]
])

print(arr_2d)

[[26  1]
 [ 0  0]
 [ 0  2]
 [ 0  3]]


In [ ]:
# View number of rows and columns
# In NumPy, the shape of an array is represented as a tuple of integers that indicate the size of each dimension of the array.
arr_2d.shape

# The matrix contains 4 rows and 2 columns

(4, 2)

In [ ]:
arr_1d.size

4

In [ ]:
# View number of elements (rows * columns)
arr_2d.size

8

In [ ]:
arr_1d.ndim

1

In [ ]:
 # View number of dimensions
arr_2d.ndim

2

# 2. Reshaping in NumPy
* Goal: How to reshape an array into various dimensions
* Examples: a 4 x 3 2-d array
 * Reshape to 12 rows and 1 column
 * Reshape to 3 rows and 4 columns
 * Reshape to 6 rows and 2 columns
 * Reshape to 2 rows and 6 columns
 * The magic **-1** in the `reshape` function

## Recall creating a 1-d array of size 6 using `np.arange()` function

In [ ]:
arr = np.arange(6)

print(arr)

[0 1 2 3 4 5]


In [ ]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

## Reshape this array to a 2 x 3 matrix

In [ ]:
# Reshape this array to 2 x 3 matrix
arr_reshape = arr.reshape(2, 3)

print(arr_reshape)

[[0 1 2]
 [3 4 5]]


## Creating a 4 x 3 Matrix

In [ ]:
# 2-d array "original"
original = np.array([
    [1, 0, 2],
    [0, 3, 0],
    [5, 0, 6],
    [0, 7, 0]
])


print(original)
print('# of rows :',  original.shape[0])
print('# of columns :',  original.shape[1])
print('size :',   original.size)

[[1 0 2]
 [0 3 0]
 [5 0 6]
 [0 7 0]]
# of rows : 4
# of columns : 3
size : 12


## Reshape to 12 rows and 1 column

In [ ]:
# Reshape to 12 rows and 1 column
reshape1 = original.reshape(12, 1)


print(reshape1)
print('# of rows :',  reshape1.shape[0])
print('# of columns :',  reshape1.shape[1])
print('size :',   reshape1.size)

[[1]
 [0]
 [2]
 [0]
 [3]
 [0]
 [5]
 [0]
 [6]
 [0]
 [7]
 [0]]
# of rows : 12
# of columns : 1
size : 12


## Reshape to 3 rows and 4 columns

In [ ]:
# Reshape to 3 rows and 4 columns
reshape2 = original.reshape(3, 4)


print(reshape2)
print('# of rows :',  reshape2.shape[0])
print('# of columns :',  reshape2.shape[1])
print('size :',   reshape2.size)

[[1 0 2 0]
 [3 0 5 0]
 [6 0 7 0]]
# of rows : 3
# of columns : 4
size : 12


## Reshape to 6 rows and 2 columns

In [ ]:
# Reshape to 6 rows and 2 columns
reshape3 = original.reshape(6, 2)


print(reshape3)
print('# of rows :',  reshape3.shape[0])
print('# of columns :',  reshape3.shape[1])
print('size :',   reshape3.size)

[[1 0]
 [2 0]
 [3 0]
 [5 0]
 [6 0]
 [7 0]]
# of rows : 6
# of columns : 2
size : 12


## Reshape to 2 rows and 6 columns

In [ ]:
# Reshape to 2 rows and 6 columns
reshape4 = original.reshape(2, 6)


print(reshape4)
print('# of rows :',  reshape4.shape[0])
print('# of columns :',  reshape4.shape[1])
print('size :',   reshape4.size)

[[1 0 2 0 3 0]
 [5 0 6 0 7 0]]
# of rows : 2
# of columns : 6
size : 12


## The magic **-1** in the `reshape` function
* `-1` in the reshape() function tells NumPy to automatically calculate the size of a dimension based on the total number of elements

In [ ]:
# 2-d array "original"
original = np.array([
    [1, 0, 2],
    [0, 3, 0],
    [5, 0, 6],
    [0, 7, 0]
])


print(original)

[[1 0 2]
 [0 3 0]
 [5 0 6]
 [0 7 0]]


In [ ]:
# Reshape to 2 rows
#  `-1` in the reshape() function tells NumPy to automatically calculate the size of a dimension based on the total number of elements
reshape5 = original.reshape(2, -1)


print(reshape5)
print('# of rows :',  reshape5.shape[0])
print('# of columns :',  reshape5.shape[1])
print('size :',   reshape5.size)

[[1 0 2 0 3 0]
 [5 0 6 0 7 0]]
# of rows : 2
# of columns : 6
size : 12


In [ ]:
# Reshape to 2 columns
reshape6 = original.reshape(-1, 2)


print(reshape6)
print('# of rows :',  reshape6.shape[0])
print('# of columns :',  reshape6.shape[1])
print('size :',   reshape6.size)

[[1 0]
 [2 0]
 [3 0]
 [5 0]
 [6 0]
 [7 0]]
# of rows : 6
# of columns : 2
size : 12


# 3. Indexing and Slicing in NumPy
* Goal: Learn indexing and slicing in NumPy
* Examples:
  * Get the first value
  * Get the last value
  * Get the 3rd row from a matrix
  * Get the 2nd column from a matrix
  * Get a sub-matrix from a matrix
  * Get the values based on conditions

## 3.1 One-dimensional array

In [ ]:
# Create a 1-d array "account_length"
account_length = np.array([107, 137, 84, 75, 63, 27, 29])

print(account_length)

[107 137  84  75  63  27  29]


### 1) Get the first value

In [ ]:
account_length[0]

107

### 2) Get the last value

In [ ]:
account_length[-1]

29

### 3）Get the 2nd to 4th elements

In [ ]:
# Start from index 1, end before index 4
account_length[1 : 4]

array([137,  84,  75])

### 4) Get even-index numbers

In [ ]:
# Get even-index numbers
# start index : end index : step
account_length[ : : 2]

array([107,  84,  63,  29])

## Challenge: Get reversing order of the original array

In [ ]:
# start index : end index : step
account_length[ : : -1]

array([ 29,  27,  63,  75,  84, 137, 107])

## 5) Get values based on conditions

In [ ]:
filter = (account_length > 30) & (account_length <= 100)

account_length_filtered = account_length[filter]

In [ ]:
# pint account_length_filtered
print(account_length_filtered)

[84 75 63]


## 3.2 Two-dimensional Array

In [ ]:
# Create 2-d array
arr_2d = np.array([
           [26, 1, 4],
           [0,  0, 6],
           [0,  2, 8],
           [0,  3, 2]
])

print(arr_2d)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


### 1) Get the first value

In [ ]:
# Get the first value
arr_2d[0, 0]

26

### 2) Get the last value

In [ ]:
# Select third element of vector
arr_2d[-1, -1]

2

### 3) Get the 3rd row from a matrix

In [ ]:
# Get the 3rd row from a matrix
arr_2d[2]

array([0, 2, 8])

In [ ]:
# Same as the below code
arr_2d[2, :]

array([0, 2, 8])

### 4) Get the 2nd column from a matrix

In [ ]:
# Get the 2nd column from a matrix
arr_2d[: , 1]

array([1, 0, 2, 3])

### 5）Get a sub-matrix from a matrix

In [ ]:
# Get a sub-matrix from a matrix
arr_2d[1: , 1:]

array([[99,  6],
       [ 2,  8],
       [ 3,  2]])

## Challenge: Assign this sub-matrix to A， and then change a number in A




In [ ]:
# Create a view of a submatrix of arr_2d
A = arr_2d[1: , 1:]

A

array([[99,  6],
       [ 2,  8],
       [ 3,  2]])

In [ ]:
# Change element at (0,0) in A
A[0, 0] = 99

In [ ]:
A

array([[99,  6],
       [ 2,  8],
       [ 3,  2]])

## What would `arr_2d` look like now?

In [ ]:
arr_2d

array([[26,  1,  4],
       [ 0, 99,  6],
       [ 0,  2,  8],
       [ 0,  3,  2]])

* When we create the array A with `A = arr_2d[1:, 1:]`, we are not creating a new array but rather creating a view or reference to a subset of the original `arr_2d`.
* Thus, `A` shares the same underlying data with `arr_2d`, which means changes made to `A` will also be reflected in `arr_2d`.

* When we modify an element in `A` using `A[0, 0] = 99`, we are actually modifying the corresponding element in the original `arr_2d` because A is a view of `arr_2d`. NumPy allows this behavior for performance reasons; it avoids unnecessary data copying.

## What if we don't want to change the original matrix `arr_2d`?
* Use `copy()`

In [ ]:
# Create 2-d array
arr_2d = np.array([
           [26, 1, 4],
           [0,  0, 6],
           [0,  2, 8],
           [0,  3, 2]
])

print(arr_2d)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


In [ ]:
# Make a copy of a submatrix of arr_2d
B = arr_2d[1: , 1:].copy()

B

array([[0, 6],
       [2, 8],
       [3, 2]])

In [ ]:
# change element at (0,0) to 100
B[0, 0] = 100

B

array([[100,   6],
       [  2,   8],
       [  3,   2]])

In [ ]:
arr_2d

array([[26,  1,  4],
       [ 0,  0,  6],
       [ 0,  2,  8],
       [ 0,  3,  2]])

### 6) Get the values based on conditions

In [ ]:
# Create 2-d array
arr_2d = np.array([
           [26, 1, 4],
           [0,  0, 6],
           [0,  2, 8],
           [0,  3, 2]
])

print(arr_2d)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


In [ ]:
# Odd numbers
filter = (arr_2d % 2 != 0)

arr_2d_filtered = arr_2d[filter]

In [ ]:
arr_2d_filtered

array([1, 3])

# Broadcasting in NumPy

## Coding Challenge: We'd like to add 10 to every element in a 2-d array.
* We want to return a 2-d array contains the new values.
* `np.empty_like(input_array)`: This function creates a new array with the same shape as `input_array` but with uninitialized elements.


In [ ]:
# def add_ten(input_arr):

In [ ]:
# Create a 2-d array
arr_2d = np.array([
                   [26, 1, 4],
                   [0,  0, 6],
                   [0,  2, 8],
                   [0,  3, 2]
  ])
# We'd like to add 10 to every number in the matrix, and we'd like to return a new matrix

## Method1(Brutal Force): Using `for` loops

In [ ]:
def add_ten(input_arr):
  # Create a new array with the same shape as the matrix but with uninitialized elements.
  output_arr = np.empty_like(input_arr)

  for row_idx in range(input_arr.shape[0]):
      for col_idx in range(input_arr.shape[1]):
          output_arr[row_idx, col_idx] = input_arr[row_idx, col_idx] + 10

  return output_arr

  # def add_ten1(input_arr: np.array) -> np.array:

In [ ]:
add_ten(arr_2d)

array([[36, 11, 14],
       [10, 10, 16],
       [10, 12, 18],
       [10, 13, 12]])

# Method 2: Broadcasting
* In simple term, broadcasting is like making sure two puzzle pieces fit together by changing one of them a bit.

In [ ]:
# Add 10 to all elements; `+ 10`
arr_2d + 10

array([[36, 11, 14],
       [10, 10, 16],
       [10, 12, 18],
       [10, 13, 12]])

## Go through another example: Example2
* multiply 1-d array to a 2-d array

In [ ]:
# Create a 2-d array : 4 * 3
arr_2d = np.array([
                   [26, 1, 4],
                   [0,  0, 6],
                   [0,  2, 8],
                   [0,  3, 2]
  ])

print(arr_2d)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


In [ ]:
# Create a 1-d array: 1 * 3
arr_1d = np.array([1, 10, 100])

print(arr_1d)

[  1  10 100]


In [ ]:
arr_2d * arr_1d

array([[ 26,  10, 400],
       [  0,   0, 600],
       [  0,  20, 800],
       [  0,  30, 200]])

## Note: It's the same as using `np.multiply()` function

In [ ]:
np.multiply(arr_2d, arr_1d)

array([[ 26,  10, 400],
       [  0,   0, 600],
       [  0,  20, 800],
       [  0,  30, 200]])

## Go through another example: Example3
* Devide 2-d array by a 2-d array

In [ ]:
# Create a 2-d array: 4 * 3
A = np.array([
                   [26, 1, 4],
                   [0,  0, 6],
                   [0,  2, 8],
                   [0,  3, 2]
  ])

print(A)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


In [ ]:
# Create another 2-d array: 4 * 1
B = np.array([
              [1],
              [3],
              [2],
              [2]
])

print(B)

[[1]
 [3]
 [2]
 [2]]


In [ ]:
A / B

array([[26. ,  1. ,  4. ],
       [ 0. ,  0. ,  2. ],
       [ 0. ,  1. ,  4. ],
       [ 0. ,  1.5,  1. ]])

## Go through another example: Example4
* sum two 2-d arrays with the same shape

In [ ]:
# Create a 2-d array: 4 * 3
A = np.array([
                   [26, 1, 4],
                   [0,  0, 6],
                   [0,  2, 8],
                   [0,  3, 2]
  ])

print(A)

[[26  1  4]
 [ 0  0  6]
 [ 0  2  8]
 [ 0  3  2]]


In [ ]:
# Create another 2-d array: 4 * 3
B = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7,  8, 9],
              [10,  11, 12]
])

print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
A + B

# Go back to slides

array([[27,  3,  7],
       [ 4,  5, 12],
       [ 7, 10, 17],
       [10, 14, 14]])

# Frequently Used Functions in Numpy

## Array Manipulation:
* M.flatten()
* np.diagonal()
* np.transpose()
* np.hstack()
* np.vstack()
* np.concatenate()
* np.append()


## Flatten an array

In [ ]:
# Create matrix
input_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

input_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
input_arr.flatten()

array([1, 2, 3, 4, 5, 6])

### Extract the main diagonal elements of an array

In [ ]:
# Create matrix
input_arr = np.array([[1, 2, 6],
                      [4, 8, 3],
                      [7, 2, 2]])

input_arr

array([[1, 2, 6],
       [4, 8, 3],
       [7, 2, 2]])

In [ ]:
# Extract the main diagonal elements of an array
np.diagonal(input_arr)

array([1, 8, 2])

## Transpose a matrix(swaps rows with columns）

In [ ]:
# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])


print("Original Matrix:")
print(matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Using numpy.transpose()
transposed_matrix = np.transpose(matrix)

# Print the transposed matrix
print("Transposed Matrix:")
print(transposed_matrix)

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Same as matrix.T
trans_m = matrix.T

print(trans_m)

[[1 4]
 [2 5]
 [3 6]]


## Stacks arrays in sequence horizontally (column-wise)

In [ ]:
arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [ ]:
arr2 = np.array([4, 5, 6])

print(arr2)

[4 5 6]


In [ ]:
stacked_arr = np.hstack((arr1, arr2))  # Stacks horizontally

print(stacked_arr)

[1 2 3 4 5 6]


### Another example

In [ ]:
arr3 = np.array([[1, 2],
                 [1, 2]])

print(arr3)

[[1 2]
 [1 2]]


In [ ]:
arr4 = np.array([[4, 4, 4],
                 [6, 6, 6]])

print(arr4)

[[4 4 4]
 [6 6 6]]


In [ ]:
stacked_arr = np.hstack((arr3, arr4))  # Stacks horizontally

print(stacked_arr)

# Number of rows should be the same

[[1 2 4 4 4]
 [1 2 6 6 6]]


## Stack arrays vertically (row-wise)

In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])

print(arr1)

[[1 2]
 [3 4]]


In [ ]:
arr2 = np.array([[5, 6]])

print(arr2)

[[5 6]]


In [ ]:
stacked_arr = np.vstack((arr1, arr2))  # Stacks vertically

print(stacked_arr)

# number of columns should be the same

[[1 2]
 [3 4]
 [5 6]]


## Concatenates two arrays - joining two or more arrays along a specified axis.



In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])

print(arr1)

[[1 2]
 [3 4]]


In [ ]:
arr2 = np.array([[5, 6],
                 [5, 6]])

print(arr2)

[[5 6]
 [5 6]]


In [ ]:
# By default, axis = 0
concat_vertical = np.concatenate((arr1, arr2))

concat_vertical

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6]])

In [ ]:
# specify axis = 1
concat_horizontal = np.concatenate((arr1, arr2), axis = 1)

concat_horizontal

array([[1, 2, 5, 6],
       [3, 4, 5, 6]])

##  Appends arrays - append values to the end of an existing array.

In [ ]:
arr1 = np.arange(8).reshape(2, 4)
print("2D arr1: \n", arr1)
print("\n Shape: ", arr1.shape)

2D arr1: 
 [[0 1 2 3]
 [4 5 6 7]]

 Shape:  (2, 4)


In [ ]:
arr2 = np.arange(8, 16).reshape(2, 4)
print("\n2D arr2: \n", arr2)
print("\n Shape: ", arr2.shape)


2D arr2: 
 [[ 8  9 10 11]
 [12 13 14 15]]

 Shape:  (2, 4)


In [ ]:
# append the arrays
# By default, array is flattened first, then append.
arr3 = np.append(arr1, arr2)
print("Append arr1, arr2 by flattened: ", arr3)

Append arr1, arr2 by flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# Append vertically
# append the arrays with axis = 0
arr4 = np.append(arr1, arr2, axis = 0)
print("Append arr1, arr2 with axis 0 : \n", arr4)

Append arr1, arr2 with axis 0 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# Append horizentally
# append the arrays with axis = 1
arr5 = np.append(arr1, arr2, axis = 1)
print("Append arr1, arr2 with axis 1 : \n", arr5)

Append arr1, arr2 with axis 1 : 
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


## Arithemetic Operations in Numpy
* np.min(), np.max()
* np.argmin(), np.argmax()
* np.unravel_index()
* np.mean(), np.std()
* np.cumsum()
* np.trace()
* np.count_nonzero()

* np.inner()
* np.cross()
* np.dot()
* np.matmul()
* np.multiply()


## Get the minimum and maximum values in an array


In [ ]:
# Create matrix
input_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

input_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.max(input_arr)

6

In [ ]:
np.min(input_arr)

1

## Get the indices of the minimum and maximum values in an array
* In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.

In [ ]:
# Create matrix
input_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])

input_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ind_max_value = np.argmax(input_arr)

In [ ]:
ind_max_value

5

In [ ]:
ind_min_value = np.argmin(input_arr)

In [ ]:
ind_min_value

0

* This function will flattern the input array first and then find the indices of the min and max values in this flatterned array

In [ ]:
arr2 = input_arr.flatten()

arr2

array([1, 2, 3, 4, 5, 6])

## How do we get the original indices of the min and max value?
* Use `np.unravel_index()` : Converts a flat index into a tuple of indices in a multi-dimensional array.

In [ ]:
## Use np.unravel_index() : Converts a flat index into a tuple of indices in a multi-dimensional array.
ind_max_value = np.argmax(input_arr)

ind_max_value

5

In [ ]:
input_arr.shape

(2, 3)

In [ ]:
np.unravel_index(ind_max_value, input_arr.shape)

(1, 2)

##  Calculate the Average of a matrix

In [ ]:
# Return mean
np.mean(input_arr)

3.5

##  Calculate the standard deviation of a matrix

In [ ]:
# Return standard deviation
np.std(input_arr)

1.707825127659933

## Compute the culmulative sum of array elements

In [ ]:
arr1 = np.array([1, 3, 4, 5, 6])

arr1

array([1, 3, 4, 5, 6])

In [ ]:
# Calculate the cumulative sum of the array
np.cumsum(arr1)

array([ 1,  4,  8, 13, 19])

## Calculate the sum along diagonals of the array


In [ ]:
arr = np.array([[1, 7, 7],
                [7, 1, 7],
                [7, 7, 1]
              ])

arr

array([[1, 7, 7],
       [7, 1, 7],
       [7, 7, 1]])

In [ ]:
# Calculate the sum along the primary diagonal
primary_diagonal_sum = np.trace(arr)

primary_diagonal_sum

3

## Counts the number of non-zero values in the array a

In [ ]:
# Create a 1D array of 8 random integers between 1 and 9
arr = np.random.randint(1, 10, 8)

arr

array([3, 2, 9, 3, 4, 8, 4, 1])

In [ ]:
# return number of non-zero values
np.count_nonzero(arr)

8

## Inner product of two arrays
* The specific behavior depends on the dimensionality of the input arrays

In [ ]:
a = np.array([1,2,3])

a

array([1, 2, 3])

In [ ]:
b = np.array([0,1,0])

b

array([0, 1, 0])

In [ ]:
# 1 * 0 + 2 * 1 + 3 * 0 = 2
np.inner(a, b)

2

* For 1-D x 1-D arrays, it computes the dot product
* For 2-D x 1-D arrays, it computes inner products for each row of the 2-D array with the 1-D array.

## Return the cross product of two (arrays of) vectors

In [ ]:
x = [1, 2, 3]

x

[1, 2, 3]

In [ ]:
y = [4, 5, 2]

y

[4, 5, 2]

In [ ]:
x

[1, 2, 3]

In [ ]:
y

[4, 5, 2]

In [ ]:
np.cross(x, y)

#  2 * 2 - 3 * 5 = -11
#  3 * 4 - 1 * 2 = 10
#  1 * 5 - 2 * 4 = -3

array([-11,  10,  -3])

## Dot product of two arrays
Specifically,

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

* If both a and b are 2-D arrays, it is matrix multiplication, but using `matmul` or `a @ b` is preferred.

In [ ]:
# 1-d arr A
A = np.array([1, 2, 3])
print(A)

[1 2 3]


In [ ]:
B = np.array([2, 1, 10])
print(B)

[ 2  1 10]


In [ ]:
print('dot product:\n', np.dot(A, B))

# 1 * 2 + 2 * 1 + 3 * 10 = 34

dot product:
 34


* In summary, while `np.dot()` is technically correct for 2-D matrix multiplication, using `np.matmul()` or `@` is recommended for better code clarity, adherence to conventions, and versatility, especially when dealing with matrices and higher-dimensional arrays in NumPy.

## Matrix product of two arrays (Matrix Multiplication)

In [ ]:
# 2-d arr A
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([[7, 8],
              [9, 10],
              [11, 12]])

b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# Calculation rule followed
print('matrix product:\n', np.matmul(a, b))


matrix product:
 [[ 58  64]
 [139 154]]


## Element-wise multiplication of two arrays (same as `*`)

In [ ]:
# 2-d arr A
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.array([1, 0, 10])

b

array([ 1,  0, 10])

In [ ]:
np.multiply(a, b)

array([[ 1,  0, 30],
       [ 4,  0, 60]])

## Other Useful Functions
* np.where()
* np.sort()

## Return elements chosen from arrays depending on condition

In [ ]:
arr = np.array([1, 2, 3, 4])

arr

array([1, 2, 3, 4])

## We want to replaces elements that are <= 2 with 0

In [ ]:
# If elements > 2 then we keep the elements, else we replaces elements <= 2 with 0
result = np.where(arr > 2, arr, 0)

result

array([0, 0, 3, 4])

In [ ]:
# Seudo code: It's the same as
if arr[i] > 2:
  keep arr[i]
  else replace arr[i] to 0

## Returns a sorted copy of an array

In [ ]:
arr = np.array([2, 1, 16, 7])

arr

array([ 2,  1, 16,  7])

In [ ]:
np.sort(arr)

array([ 1,  2,  7, 16])