# Numpy

- Numpy is a Python library that provides support for large, multi-dimensional arrays and matrices.
- Numpy offers a large collection of high-level mathematical functions to operate on arrays.
- Speed: Numpy is faster than regular python lists
- Easy Functions: Numpy provides lot of built-in functionalities that make mathematical calculations easy
- Efficiency - Perform operations on entire lists of data without having to use loops

# Numpy - ndarray
> - At the core of Numpy package, is the ndarray object  
> - This encapsulates n-dimensional **array of homogeneous data types** (data types of (only one type) all are same, only int or str)

### What is the difference between lists vs ndarray?
- Fixed size at creation unlike lists (which can grow dynamically)
- Numpy elements are of same data type, thus same size of memory
- Numpy facilitates advanced matematical and other types of operations on large numbers of data

### Why is Numpy fast?
- 2 reasons (1. Vectorization & 2. Broadcasting)
- Vectorization - absence of any explicit looping, indexing etc, in the code.
                - These things are "behind the scene" in optimized precompiled C code
- Broadcasting - describes the implicit element-by-element behaviour of operations.
              - all operations, not just arithmetic operations, behave in this implicit element-by-element fashion, i.e., they broadcast


### Important attributes of ndarray
- ndarray.ndim => Number of axes (dimensions) in the array
- ndarray.shape => tuple of all dimension as shape, example matrix it returns tuple of (mxn) m rows, n columns
- ndarray.size => total number of elements in the ndarray
- ndarray.dtype => data type stored in ndarray

### Reshaping array
- Using arr.reshape() => gives new shape to array without changing the data and size. 
    before and after same array elements with different shape.

### Indexing & Slicing
- Same indexing and slicing as python, examples are below
    data = np.array[1, 2, 3]
    data[1] => 2
    data[0:2] => [1, 2]
    data [1:] => [2, 3]
    data[-2:] =>[2, 3]

In [ ]:
import numpy as np

In [ ]:
# How to create our one dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Properties associated with numpy ndarray
print(f"Shape: {arr1.shape}")
print(f"NDim: {arr1.ndim}")
print(f"Size: {arr1.size}")
print(f"Type: {arr1.dtype}")
print(f"Data: {arr1.itemsize}")

In [ ]:
# How to create our two dimensional array
arr2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])
print(arr2)

# Properties associated with numpy ndarray
print(f"Shape: {arr2.shape}")
print(f"NDim: {arr2.ndim}")
print(f"Size: {arr2.size}")
print(f"Type: {arr2.dtype}")
print(f"Data: {arr2.itemsize}")

In [ ]:
# Reshaping the array

# Create 3 dimensional array
arr3 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55], [111, 222, 333, 444, 555]])
print(arr3)
print(f"arr3 shape {arr3.shape}")

print(f"-----------------------------------") # Divder

# Reshape the array
r_arr3 = arr3.reshape(5, 3)
print(r_arr3)

print(f"-----------------------------------") # Divder

# Supposed to get an error while doing reshape of not equivalent size
try:
    r_arr3 = arr3.reshape(5, 2)
    print(r_arr3)
except Exception as ex:
    print(f"{type(ex).__name__} : {ex} : {ex.args}")

print(f"-----------------------------------") # Divder

r_arr3 = arr3.reshape(15, 1)
print(r_arr3)

In [ ]:
# indexing and slicing numpy arryas
## Numpy indexing and slicing is the same as python lists

data = np.array([1, 2, 3, 4, 5])
data


In [ ]:
data[0]

In [ ]:
data[0:2]

In [ ]:
data[-2:]

In [ ]:
# Methods to create an fast array

np.zeros(10, dtype=np.int32)

In [ ]:
np.ones(10, dtype=np.int32)

In [ ]:
# Create an array with starting value 2 and ending value 50 with the step count as 3
np.arange(2, 50, 3)

In [ ]:
# starting, end value and how many values between the starting and ending
np.linspace(0, 10, num=5)

In [ ]:
# Sorting an array in numpy array
arr4 = np.array([12,8, 15, 20, 3, 1, 4, 5, 6, 9, 11])
np.sort(arr4)


In [ ]:
# Arrays can be concatenated

x = np.array([[1,2], [3,4]])
y = np.array([[5, 8], [7,9]])

print(x)
print("------------")
print(y)
print("------------")
print(np.concatenate((x, y), axis=0))

In [ ]:
# Basic array operations

arr1 = np.array([1, 2])
arr2 = np.ones(2, dtype=np.int32)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

In [ ]:
# Summation of values in an array
M = np.arange(2, 20, 2)
print(M)
print(f"sum: {M.sum()}")
print(f"min: {M.min()}")
print(f"max: {M.max()}")
print(f"mean: {M.mean()}")


In [ ]:
# Broadcasting
M = np.arange(2, 20, 2)
print(f"broadcast multiplication {M * 3.14}")

In [ ]:
# Filtering in numpy arrays

M = np.array([10, 12, 8, 5, 1, 7,22, 40, 6, 9, 89, 70])
print(M > 20)
print(M[M > 20])
print(M[M <= 9])
print(M[(M >=10) & (M <= 30)])


In [ ]:
# How to save and load numpy objects
M = np.array([10, 12, 8, 5, 1, 7,22, 40, 6, 9, 89, 70])

print(M)

np.save("random_array_2_save", M)

In [ ]:
! ls

In [ ]:
# Save numpy as numpy object
arr_load = np.load("random_array_2_save.npy")
print(arr_load)

In [ ]:
# Save file as csv
M = np.array([10, 12, 8, 5, 1, 7,22, 40, 6, 9, 89, 70])
print(M)
np.savetxt("random_array_2_save_as_csv", M)

In [ ]:
! cat random_array_2_save_as_csv


In [ ]:
arr_load = np.loadtxt("random_array_2_save_as_csv")
print(arr_load)

In [ ]:
import numpy as np

# arr = np.array([[1, 2, 1], [2,1,1], [-1,2,1]])
M = np.array([[2,1,5], [1,3,1], [3,4,6]])
#sol = np.array([10, 4, 8])

# sol = sol.reshape(1,3)

print(M)
print(np.shape(M))
#print(sol)
#print(np.shape(sol))
print(f"{np.linalg.matrix_rank(M)}")
#print(np.linalg.solve(arr, sol))
#print(f"{np.linalg.det(arr): .3f}")



In [1]:
import numpy as np

def swap_rows(M, from_row, to_row):
    """
    Swap rows in the given matrix.
    """
    # Copy matrix M so the changes do not affect the original matrix. 
    M = M.copy()
    # Swap indexes
    M[[to_row, from_row]] = M[[from_row, to_row]]
    return M


def get_index_of_first_non_zero_value_from_column(N, column, starting_row):
    """
    Retrieve the index of the first non-zero value in a specified column of the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to search for non-zero values.
    - column (int): The index of the column to search.
    - starting_row (int): The starting row index for the search.

    Returns:
    int: The index of the first non-zero value in the specified column, starting from the given row.
                Returns -1 if no non-zero value is found.
    """
    # Get the column array starting from the specified row
    column_array = N[starting_row:,column]
    for index, val in enumerate(column_array):
        # Iterate over every value in the column array. 
        # To check for non-zero values, you must always use np.isclose instead of doing "val == 0".        
        if not np.isclose(val, 0, atol=1e-5):
            # If one non zero value is found, then adjust the index to match the correct index in the matrix and return it.
            index = index + starting_row
            return index
    # If no non-zero value is found below it, return -1.       
    return -1

def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    """
    Find the index of the first non-zero value in the specified row of the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to search for non-zero values.
    - row (int): The index of the row to search.
    - augmented (bool): Pass this True if you are dealing with an augmented matrix, 
                        so it will ignore the constant values (the last column in the augmented matrix).

    Returns:
    int: The index of the first non-zero value in the specified row.
                Returns -1 if no non-zero value is found.
    """

    # Create a copy to avoid modifying the original matrix
    M = M.copy()


    # If it is an augmented matrix, then ignore the constant values
    if augmented == True:
        # Isolating the coefficient matrix (removing the constant terms)
        M = M[:,:-1]
        
    # Get the desired row
    row_array = M[row]
    for i, val in enumerate(row_array):
        # If finds a non zero value, returns the index. Otherwise returns -1.
        if not np.isclose(val, 0, atol = 1e-5):
            return i
    return -1

def augmented_matrix(A, B):
    """
    Create an augmented matrix by horizontally stacking two matrices A and B.

    Parameters:
    - A (numpy.array): First matrix.
    - B (numpy.array): Second matrix.

    Returns:
    - numpy.array: Augmented matrix obtained by horizontally stacking A and B.
    """
    augmented_M = np.hstack((A,B))
    return augmented_M

############################################
# # Test swap_row method
# M = np.array([[0, 8, 6, 4], [0, 0, 0, 3], [0, 0, 5, 9], [6, 4, 8, 1]])
# print(f"original: {M}")
# swapped_row = swap_rows(M, 0, 3)
# print(f"switched rows: {swapped_row}")
# swapped_row = swap_rows(swapped_row, 1, 3)
# print(f"switched rows: {swapped_row}")
############################################
# # Test get_index_of_first_non_zero_value_from_column
# # and
# # Test get_index_first_non_zero_value_from_row
# N = np.array([
# [0, 5, -3 ,6 ,8],
# [0, 6, 3, 8, 1],
# [0, 0, 0, 0, 0],
# [0, 0, 0 ,0 ,7],
# [0, 2, 1, 0, 4]
# ]
# )
# print(f"original: {N}")

# print(get_index_of_first_non_zero_value_from_column(N, 0, 0))
# print(get_index_of_first_non_zero_value_from_column(N, 1, 2))
# print(get_index_of_first_non_zero_value_from_column(N, -1, 2))
# print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
# print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')
# print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')
########################################################################################
# Test augmented_matrix

A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))
############################################




[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


In [2]:
def row_echelon_form(A, B):
    """
    Utilizes elementary row operations to transform a given set of matrices, 
    which represent the coefficients and constant terms of a linear system, into row echelon form.

    Parameters:
    - A (numpy.array): The input square matrix of coefficients.
    - B (numpy.array): The input column matrix of constant terms

    Returns:
    numpy.array: A new augmented matrix in row echelon form with pivots as 1.
    """
    
    # Before any computation, check if matrix A (coefficient matrix) has non-zero determinant. 
    # It will be used the numpy sub library np.linalg to compute it.

    det_A = np.linalg.det(A)

    # Returns "Singular system" if determinant is zero
    if np.isclose(det_A, 0) == True:
        return 'Singular system'

    # Make copies of the input matrices to avoid modifying the originals
    A = A.copy()
    B = B.copy()


    # Convert matrices to float to prevent integer division
    A = A.astype('float64')
    B = B.astype('float64')

    # Number of rows in the coefficient matrix
    num_rows = len(A) 

    ### START CODE HERE ###

    # Transform matrices A and B into the augmented matrix M
    M = augmented_matrix(A, B)
    
    # Iterate over the rows.
    for row in range(num_rows):

        # The first pivot candidate is always in the main diagonal, let's get it. 
        # Remember that the diagonal elements in a matrix has the same index for row and column. 
        # You may access a matrix value by typing M[row, column]. In this case, column = None
        pivot_candidate = M[row, row]

        # If pivot_candidate is zero, it cannot be a pivot for this row. 
        # So the first step you need to take is to look at the rows below it to check if there is a non-zero element in the same column.
        # The usage of np.isclose is a good practice when comparing two floats.
        if np.isclose(pivot_candidate, 0) == True: 
            # Get the index of the first non-zero value below the pivot_candidate. 
            first_non_zero_value_below_pivot_candidate = get_index_of_first_non_zero_value_from_column(M, row, row) 

            # Swap rows
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate) 

            # Get the pivot, which is in the main diagonal now 
            pivot = M[row,row] 
        
        # If pivot_candidate is already non-zero, then it is the pivot for this row
        else:
            pivot = pivot_candidate 
        
        # Now you are ready to apply the row reduction in every row below the current
            
        # Divide the current row by the pivot, so the new pivot will be 1. You may use the formula current_row -> 1/pivot * current_row
        # Where current_row can be accessed using M[row].
        M[row] = (1/pivot) * M[row]

        # Perform row reduction for rows below the current row
        for j in range(row + 1, num_rows): 
            # Get the value in the row that is below the pivot value. 
            # Remember that, since you are dealing only with non-singular matrices, the pivot is in the main diagonal.
            # Therefore, the values in row j that are below the pivot, must have column index the same index as the column index for the pivot.
            value_below_pivot = M[j,row]
            
            # Perform row reduction using the formula:
            # row_to_reduce -> row_to_reduce - value_below_pivot * pivot_row
            M[j] = M[j] - value_below_pivot*M[row]
            
    ### END CODE HERE ###

    return M



########################################################################################
# Test row_echelon_form
A = np.array([[0, 2, 1], [1, 1, 1], [1, 2, 1]])
B = np.array([[3], [6], [12]])
print(row_echelon_form(A,B))


A1 = np.array([[1,2,3],[0,1,0], [0,0,5]])
B1 = np.array([[1], [2], [4]])
print(row_echelon_form(A1,B1))

########################################################################################

[[ 1.   1.   1.   6. ]
 [ 0.   1.   0.5  1.5]
 [-0.  -0.   1.  -9. ]]
[[1.  2.  3.  1. ]
 [0.  1.  0.  2. ]
 [0.  0.  1.  0.8]]


In [4]:
# GRADED FUNCTION: back_substitution

def back_substitution(M):
    """
    Perform back substitution on an augmented matrix (with unique solution) in reduced row echelon form to find the solution to the linear system.

    Parameters:
    - M (numpy.array): The augmented matrix in row echelon form with unitary pivots (n x n+1).

    Returns:
    numpy.array: The solution vector of the linear system.
    """
    
    # Make a copy of the input matrix to avoid modifying the original
    M = M.copy()

    # Get the number of rows (and columns) in the matrix of coefficients
    num_rows = M.shape[0]

    ### START CODE HERE ####
    
    # Iterate from bottom to top
    for row in reversed(range(num_rows)): 
        substitution_row = row

        # Get the index of the first non-zero element in the substitution row. Remember to pass the correct value to the argument augmented.
        index = get_index_first_non_zero_value_from_row(M, row)

        # Iterate over the rows above the substitution_row
        for j in range(row): 

            # Get the row to be reduced. The indexing here is similar as above, with the row variable replaced by the j variable.
            row_to_reduce = M[[j]]

            # Get the value of the element at the found index in the row to reduce
            value = row_to_reduce[0, index]
            
            # Perform the back substitution step using the formula row_to_reduce -> row_to_reduce - value * substitution_row
            row_to_reduce = row_to_reduce - (value * M[[substitution_row]])

            # Replace the updated row in the matrix, be careful with indexing!
            M[j,:] = row_to_reduce

    ### END CODE HERE ####

     # Extract the solution from the last column
    solution = M[:,-1]
    
    return solution


########################################################################################
# Test row_echelon_form
# and
# Test back_substitution

# A = np.array([[0, 2, 1], [1, 1, 1], [1, 2, 1]])
# B = np.array([[3], [6], [12]])
# reAB = row_echelon_form(A,B)
# print(f"row echelon form of A & B: {reAB}")

# bsAB = back_substitution(reAB)
# print(f"back substituted row echolon reduced form of A & B: {bsAB}")



A1 = np.array([[1,2,3],[0,1,0], [0,0,5]])
B1 = np.array([[1], [2], [4]])
reA1B1 = row_echelon_form(A1,B1)
print(f"row echelon form of A1 & B1: {reA1B1}")

bsA1B1 = back_substitution(reA1B1)
print(f"back substituted row echolon reduced form of A1 & B1: {bsA1B1}")


########################################################################################


row echelon form of A1 & B1: [[1.  2.  3.  1. ]
 [0.  1.  0.  2. ]
 [0.  0.  1.  0.8]]
back substituted row echolon reduced form of A1 & B1: [-5.4  2.   0.8]


In [ ]:
def gaussian_elimination(A, B):
    """
    Solve a linear system represented by an augmented matrix using the Gaussian elimination method.

    Parameters:
    - A (numpy.array): Square matrix of size n x n representing the coefficients of the linear system
    - B (numpy.array): Column matrix of size 1 x n representing the constant terms.

    Returns:
    numpy.array or str: The solution vector if a unique solution exists, or a string indicating the type of solution.
    """
    
    ### START CODE HERE ###

    # Get the matrix in row echelon form
    row_echelon_M = row_echelon_form(A, B)

    # If the system is non-singular, then perform back substitution to get the result. 
    # Since the function row_echelon_form returns a string if there is no solution, let's check for that.
    # The function isinstance checks if the first argument has the type as the second argument, returning True if it does and False otherwise.
    if not isinstance(row_echelon_M, str): 
        solution = back_substitution(row_echelon_M)

    ### END SOLUTION HERE ###

    return solution

In [14]:
import numpy as np

# arr = np.array([[0.25, -0.25], [-0.125, 0.625]])
# arr = np.array([[1, 0], [2, 3]])
arr = np.array([[1, 3, 4], [2, -1, -3], [4, 5, -11]])
# arr = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
# arr1 = np.array([[2, 8, 7], [4, 3, 9], [1, 9, 5]])

print(np.linalg.matrix_rank(arr))
print(f"{np.linalg.det(arr):.2f}")

3
112.00
